version: "3.9"

services:
  scryfall-server:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - "8085:8085"

networks:
  default:
    external: true
    name: infra_infra